### ISSUE TITLE
Advanced XC Queries are not working for me

### ISSUE THREAD

**Issue by michaelschwob** [maRce10/warbleR#60]
I have 3 XC queries in the following code, all of which return 7 items. The first query should return 7. The second and third should return 2 and 1, respectively. However, the latter two queries still provide the same results as if the `loc` and `year` tags are being ignored. How can I correctly filter the results to obtain the 2 and 1, respectively?

Technical notes: R version (4.3.1) and warbleR version (1.1.29)

```
####
#### Reading Data from Xeno-canto
####

library(warbleR)

## get ostrich data
all_ostrich = query_xc('struthio camelus', download = TRUE)

## get ostrich data in a specific area
limpopo_ostrich = query_xc(qword = 'gen:struthio loc:"mmabolela reserve"', download = TRUE)

## get ostrich data from a specific time period with the highest quality
good_ostrich = query_xc("gen:struthio year:2019", download = TRUE)
```

**Comment by costantinicarlo** [comment]
I have the same issue (R 4.2.3 running in RStudio 2023.09.0+463, warbleR 1.1.29).

In fact even the advanced query example provided in the help of the `query_xc` function

`orth.pap <- query_xc(qword = "gen:orthonyx cnt:papua loc:tari", download = FALSE)`

returns a dataset of genus *Orthonyx* that has not taken into account the multiple filter criteria for country and locality (i.e. 98 instead of 6 records, as of today).

Below, I have isolated the portion of the `query_xc` function pasting the query string into the URL request

```
if (grepl("\\:", qword)) {
  first_colon_pos <- gregexpr(":", qword)[[1]][1]
  spaces_pos <- gregexpr(" ", qword)[[1]]
  if (length(spaces_pos) > 1) {
    if (all(spaces_pos[1:2] < first_colon_pos)) {
      qword <- paste0(substr(qword, start = 0, stop = spaces_pos - 
                               1), "%20", substr(qword, start = spaces_pos + 
                                                 1, stop = nchar(qword)))
    }
  }
  qword <- gsub(" ", "&", qword)
}
else {
  qword <- gsub(" ", "%20", qword)
}

q <- rjson::fromJSON(file = paste0("https://www.xeno-canto.org/api/2/recordings?query=", 
                                   qword))
```

when `qword <- "gen:orthonyx cnt:papua loc:tari"` and you run it through the portion of code above, the `qword` string pasted into the query is `gen:orthonyx&cnt:papua&loc:tari`, not `gen:orthonyx%20cnt:papua%20loc:tari`.

This is where I think the error comes from.

**Comment by michaelschwob** [comment]
Good find!

**Comment by auman-chan** [comment]
I found that the format of api query had been updated in 2023 (see https://xeno-canto.org/explore/api). Now the connector of query is "+" instead of "&" and "%20".
I use the new format to search for items above (R 4.1.3 running in RStudio 2023.06.01+524, warbleR 1.1.29), and get the result like this:
```
limpopo_ostrich = query_xc(qword = 'gen:struthio+loc:"mmabolela reserve"', download = F)
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s  
2 recording(s) found!

good_ostrich = query_xc('gen:struthio+year:2019', download = F)   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=02s   
7 recording(s) found!

all_ostrich = query_xc('struthio camelus', download = F)
  |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed=06s  
38 recording(s) found!
```
The first one works well, and the second query gets extra 6 items because someone uploaded recordings in 2019 on Dec 2023.
So maybe the code of `query_xc` should be updated to fit the new format of api

**Comment by maRce10** [comment]
OK I updated the function. Just a heads up that I am moving this functions to the package suwo (https://github.com/maRce10/suwo) . it has functions to query other repositories
